// automatically generated by the FlatBuffers compiler, do not modify (manually updated for schema redefinition)

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub mod tanuki {
  pub mod irminsul {
    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

pub enum ConceptVectorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ConceptVector<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ConceptVector<'a> {
  type Inner = ConceptVector<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ConceptVector<'a> {
  pub const VT_V: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn view(buf: &'a [u8], loc: usize) -> Self {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }

  #[inline]
  pub fn v(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(ConceptVector::VT_V, None) }
  }
}

impl<'a> flatbuffers::Verifiable for ConceptVector<'a> {
  #[inline]
  fn run_verifier(
    _v: &mut flatbuffers::Verifier, _pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    Ok(())
  }
}

pub struct ConceptVectorArgs<'a> {
    pub v: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for ConceptVectorArgs<'a> {
  #[inline]
  fn default() -> Self {
    ConceptVectorArgs {
      v: None,
    }
  }
}
pub struct ConceptVectorBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ConceptVectorBuilder<'a, 'b> {
  #[inline]
  pub fn add_v(&mut self, v: flatbuffers::WIPOffset<flatbuffers::Vector<'b, f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ConceptVector::VT_V, v);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ConceptVectorBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ConceptVectorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ConceptVector<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum ASTNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ASTNode<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ASTNode<'a> {
  type Inner = ASTNode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ASTNode<'a> {
  pub const VT_NODE_ID: flatbuffers::VOffsetT = 4;
  pub const VT_MERKLE_HASH: flatbuffers::VOffsetT = 6;
  pub const VT_PARENT_ID: flatbuffers::VOffsetT = 8;
  pub const VT_CHILD_COUNT: flatbuffers::VOffsetT = 10;
  pub const VT_DESCENDANT_COUNT: flatbuffers::VOffsetT = 12;
  pub const VT_TITLE: flatbuffers::VOffsetT = 14;
  pub const VT_CONCEPT: flatbuffers::VOffsetT = 16;
  pub const VT_RAW_LOGIC: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn view(buf: &'a [u8], loc: usize) -> Self {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }

  #[inline]
  pub fn node_id(&self) -> u64 {
    unsafe { self._tab.get::<u64>(ASTNode::VT_NODE_ID, Some(0)).unwrap() }
  }
  #[inline]
  pub fn merkle_hash(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(ASTNode::VT_MERKLE_HASH, None) }
  }
  #[inline]
  pub fn parent_id(&self) -> u64 {
    unsafe { self._tab.get::<u64>(ASTNode::VT_PARENT_ID, Some(0)).unwrap() }
  }
  #[inline]
  pub fn child_count(&self) -> u32 {
    unsafe { self._tab.get::<u32>(ASTNode::VT_CHILD_COUNT, Some(0)).unwrap() }
  }
  #[inline]
  pub fn descendant_count(&self) -> u32 {
    unsafe { self._tab.get::<u32>(ASTNode::VT_DESCENDANT_COUNT, Some(0)).unwrap() }
  }
  #[inline]
  pub fn title(&self) -> Option<&'a str> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ASTNode::VT_TITLE, None) }
  }
  #[inline]
  pub fn concept(&self) -> Option<ConceptVector<'a>> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<ConceptVector>>(ASTNode::VT_CONCEPT, None) }
  }
  #[inline]
  pub fn raw_logic(&self) -> Option<&'a str> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ASTNode::VT_RAW_LOGIC, None) }
  }
}

impl<'a> flatbuffers::Verifiable for ASTNode<'a> {
  #[inline]
  fn run_verifier(
    _v: &mut flatbuffers::Verifier, _pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    Ok(())
  }
}

pub struct ASTNodeArgs<'a> {
    pub node_id: u64,
    pub merkle_hash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub parent_id: u64,
    pub child_count: u32,
    pub descendant_count: u32,
    pub title: Option<flatbuffers::WIPOffset<&'a str>>,
    pub concept: Option<flatbuffers::WIPOffset<ConceptVector<'a>>>,
    pub raw_logic: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ASTNodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    ASTNodeArgs {
      node_id: 0,
      merkle_hash: None,
      parent_id: 0,
      child_count: 0,
      descendant_count: 0,
      title: None,
      concept: None,
      raw_logic: None,
    }
  }
}
pub struct ASTNodeBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ASTNodeBuilder<'a, 'b> {
  #[inline]
  pub fn add_node_id(&mut self, node_id: u64) {
    self.fbb_.push_slot::<u64>(ASTNode::VT_NODE_ID, node_id, 0);
  }
  #[inline]
  pub fn add_merkle_hash(&mut self, merkle_hash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ASTNode::VT_MERKLE_HASH, merkle_hash);
  }
  #[inline]
  pub fn add_parent_id(&mut self, parent_id: u64) {
    self.fbb_.push_slot::<u64>(ASTNode::VT_PARENT_ID, parent_id, 0);
  }
  #[inline]
  pub fn add_child_count(&mut self, child_count: u32) {
    self.fbb_.push_slot::<u32>(ASTNode::VT_CHILD_COUNT, child_count, 0);
  }
  #[inline]
  pub fn add_descendant_count(&mut self, descendant_count: u32) {
    self.fbb_.push_slot::<u32>(ASTNode::VT_DESCENDANT_COUNT, descendant_count, 0);
  }
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ASTNode::VT_TITLE, title);
  }
  #[inline]
  pub fn add_concept(&mut self, concept: flatbuffers::WIPOffset<ConceptVector<'b>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ASTNode::VT_CONCEPT, concept);
  }
  #[inline]
  pub fn add_raw_logic(&mut self, raw_logic: flatbuffers::WIPOffset<&'b str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ASTNode::VT_RAW_LOGIC, raw_logic);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ASTNodeBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ASTNodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ASTNode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum MemoryRootOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MemoryRoot<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MemoryRoot<'a> {
  type Inner = MemoryRoot<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MemoryRoot<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_ACTIVE_NODES: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn view(buf: &'a [u8], loc: usize) -> Self {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }

  #[inline]
  pub fn version(&self) -> u32 {
    unsafe { self._tab.get::<u32>(MemoryRoot::VT_VERSION, Some(0)).unwrap() }
  }
  #[inline]
  pub fn active_nodes(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ASTNode<'a>>>> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ASTNode<'a>>>>>(MemoryRoot::VT_ACTIVE_NODES, None) }
  }
}

impl<'a> flatbuffers::Verifiable for MemoryRoot<'a> {
  #[inline]
  fn run_verifier(
    _v: &mut flatbuffers::Verifier, _pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    Ok(())
  }
}

pub struct MemoryRootArgs<'a> {
    pub version: u32,
    pub active_nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ASTNode<'a>>>>>,
}
impl<'a> Default for MemoryRootArgs<'a> {
  #[inline]
  fn default() -> Self {
    MemoryRootArgs {
      version: 0,
      active_nodes: None,
    }
  }
}
pub struct MemoryRootBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MemoryRootBuilder<'a, 'b> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(MemoryRoot::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_active_nodes(&mut self, active_nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<ASTNode<'b>>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MemoryRoot::VT_ACTIVE_NODES, active_nodes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MemoryRootBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MemoryRootBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MemoryRoot<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_memory_root<'a>(buf: &'a [u8]) -> MemoryRoot<'a> {
  flatbuffers::root::<MemoryRoot<'a>>(buf).unwrap()
}

#[inline]
pub fn get_size_prefixed_root_as_memory_root<'a>(buf: &'a [u8]) -> MemoryRoot<'a> {
  flatbuffers::size_prefixed_root::<MemoryRoot<'a>>(buf).unwrap()
}

#[inline]
pub fn finish_memory_root_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<MemoryRoot<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_memory_root_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<MemoryRoot<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
  }
}
