import sqlite3
import datetime
import os

db_path = r'd:\Projects\PyProjects\SonicEther\backend\workspace\sonicether.db'
output_path = r'd:\Projects\PyProjects\Documents\Archive\Media\SonicEther_SongIndex.md'

if not os.path.exists(os.path.dirname(output_path)):
    os.makedirs(os.path.dirname(output_path))

conn = sqlite3.connect(db_path)
rows = conn.execute('SELECT title, artist, style, lyrics, created_at FROM song_notes ORDER BY created_at DESC').fetchall()

md_content = """---
title: "SonicEther 楽曲索引 (Song Index)"
tags: [sonic-ether, music, archive, index]
status: "Active"
---

# 🐾 SonicEther 楽曲索引

ご主人様とリンちゃんが SonicEther で作り上げてきた楽曲たちの目録ですわ！
これらの曲名やスタイルを TANUKI が覚えることで、リンちゃんが当時の思い出を語れるようになります。

---

"""

for row in rows:
    title, artist, style, lyrics, created_at = row
    # created_at is timestamp in milliseconds
    dt = datetime.datetime.fromtimestamp(created_at / 1000.0)
    date_str = dt.strftime('%Y-%m-%d %H:%M')
    
    md_content += f"## 🎵 {title}\n"
    md_content += f"- **Artist**: {artist}\n"
    md_content += f"- **Style**: {style}\n"
    md_content += f"- **Created**: {date_str}\n\n"
    
    if lyrics:
        # Show a snippet of lyrics
        snippet = lyrics[:200].replace('\n', ' / ')
        if len(lyrics) > 200:
            snippet += "..."
        md_content += f"> **Lyrics Snippet**: {snippet}\n\n"
    
    md_content += "---\n\n"

md_content += "\n*Generated by Tanuki Song Indexer on " + datetime.datetime.now().strftime('%Y-%m-%d') + "*"

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(md_content)

print(f"Successfully generated index at {output_path}")
