use tanuki_core::db::TanukiDb;
use anyhow::Result;
use std::path::Path;
use std::fs;

fn sanitize_component(name: &str) -> String {
    let forbidden = ['/', '\\', ':', '*', '?', '"', '<', '>', '|', '#'];
    let mut safe = name.chars()
        .map(|c| if c.is_control() || forbidden.contains(&c) { '_' } else { c })
        .collect::<String>();
    
    // Length limit for each component (shortened for Windows safety)
    if safe.chars().count() > 80 {
        safe = safe.chars().take(80).collect::<String>();
    }
    
    // Windows restricts trailing dots and spaces
    safe = safe.trim().trim_end_matches('.').to_string();
    
    if safe.is_empty() {
        safe = "unnamed".to_string();
    }
    
    safe
}

fn sanitize_path(raw_path: &str) -> String {
    // ">" や " / " を区切り文字として扱う
    let raw_path = raw_path.replace(" > ", "/").replace(" / ", "/");
    let components: Vec<String> = raw_path.split('/')
        .map(|c| sanitize_component(c))
        .collect();
    
    components.join("/")
}

pub fn generate_tree(db: &TanukiDb, output_dir: &str) -> Result<()> {
    println!("Starting Tree Generation (Backend)...");
    
    let root = std::env::current_dir().unwrap().join(output_dir);
    if let Err(e) = fs::create_dir_all(&root) {
        println!("  ⚠️ Failed to create root output dir: {:?} ({})", root, e);
        return Err(e.into());
    }

    // 1. クラスタを取得してディレクトリと INDEX.md を作成
    let clusters = db.get_all_clusters()?;
    let mut root_index_content = String::from(
        "# 🐾 T.A.N.U.K.I. 知識ベース・ルートインデックス\n\nご主人様、知識ベースのルートインデックスですわ！以下のクラスタから必要な情報を探索してくださいね。\n\n## 📂 ナレッジクラスタ一覧\n"
    );

    for cluster in clusters {
        let rel_path = sanitize_path(&cluster.id);
        let cluster_dir = root.join(&rel_path);
        
        if let Err(e) = fs::create_dir_all(&cluster_dir) {
            println!("    ⚠️ Failed to create dir: {:?} ({})", cluster_dir.canonicalize().unwrap_or(cluster_dir.clone()), e);
            continue;
        }

        let index_path = cluster_dir.join("INDEX.md");
        let content = format!(
            "# {}\n\n## Summary\n{}\n\n## Navigation Criteria\n{}\n\n---\n*Generated by T.A.N.U.K.I. Backend*",
            cluster.title, cluster.summary, cluster.criteria
        );
        if let Err(e) = fs::write(&index_path, content) {
             println!("    ⚠️ Failed to write index: {:?} ({})", index_path, e);
        } else {
             println!("    ✓ Created cluster index: {}", rel_path);
        }

        // ルートインデックスへの追加
        root_index_content.push_str(&format!("- [[{}|{}]]\n", rel_path, cluster.title));
    }

    // ルート INDEX.md の書き込み
    root_index_content.push_str("\n---\n*Generated by T.A.N.U.K.I. Backend*");
    let root_index_path = root.join("INDEX.md");
    if let Err(e) = fs::write(&root_index_path, root_index_content) {
        println!("  ⚠️ Failed to write root index: {:?} ({})", root_index_path, e);
    } else {
        println!("  ✓ Created root index.md!");
    }

    // 2. ノードを取得してファイルを生成
    let nodes = db.get_all_nodes()?;
    for node in nodes {
        let rel_path = sanitize_path(&node.context_path);
        let cluster_dir = root.join(&rel_path);
        
        if let Err(e) = fs::create_dir_all(&cluster_dir) {
            println!("    ⚠️ Failed to create node dir: {:?} ({})", cluster_dir, e);
            continue;
        }
        
        // ファイル名もサニタイズ
        let safe_id = sanitize_component(&node.id);
        let file_name = format!("{}.md", safe_id);
        let file_path = cluster_dir.join(file_name);
        
        let content = format!(
            "# {}\n\n## AI Summary\n{}\n\n## Content\n{}\n\n## Metadata\n```json\n{}\n```\n\n---\n*Path: {}*",
            node.title, node.summary, node.content, node.metadata, node.context_path
        );
        
        if let Err(e) = fs::write(&file_path, content) {
            println!("    ⚠️ Failed to write file: {:?} ({})", file_path, e);
            continue;
        }
        println!("    ✓ Created node file: {}/{}", rel_path, safe_id);
    }

    println!("Tree Generation complete at: {}", output_dir);
    Ok(())
}
